### ISSUE TITLE
HELP: Outliers mean temperature plot !

### ISSUE THREAD

**Issue by Jeifel** [data-hydenv/Excercise-06#10]
Hey,

we want to visualise your/our data, showing the min, max and mean in the plot. Some hobos have unusually high temperature values in the beginning of the campaign (probably left inside too long), which affects the plot. This also occurs on the last day and for some hobos at midday (see picture).

Especially Hobos Nr.: 10350032 and 10347346 are affected.

Our question/issue is, how we should process this? Leave this data in, crop these hobos out, repeat the quality control, or something completely different?

Thanks in advance!

![Mean_Temp](https://user-images.githubusercontent.com/59614100/72623684-e5412580-3945-11ea-97f4-d0ebe91e178d.png)

**Comment by mmaelicke** [comment]
[![](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/Leave%20the%20data%20in)](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/Leave%20the%20data%20in/vote)
[![](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/crop%20the%20hobos%20out)](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/crop%20the%20hobos%20out/vote)
[![](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/redo%20quality%20control)](https://api.gh-polls.com/poll/01DYT61VVNXX7R71PB39CREYC6/redo%20quality%20control/vote)

**Comment by AmadeusL** [comment]
This also applies to the end of the measurement series as the HOBOs kept on recording (indoors) until we connected them to the computer.

**Comment by modche** [comment]
Hi everybody. 
Really nice to see how you all work with github ressources this week and that a lot of topics are discussed here. Great job!

Regarding the HOBOs: Firstly, is this plot done with 10-minute values or with the 1-hour values? In the 1-hour series all the indoor temperature at beginning/at the end should be removed. However, for the 10-minute raw data there might be a lot of "outliers" or strange temperature ranges. At the moment we do not have any quality check considering indoor temperatures (perhaps minimum hourly variability), but as I mentioned those indoor-periods should have been removed manually for each location (by the person who used the HOBO, of course).

Could you come up with two lines in the plot, one representing the data you trust and that look quite reasonable, one for all the supicious HOBOs - so, then you can compare both lines...

Note, some HOBOs might really be influences by sunlight, but this data should stay in such a plot. Perhaps here the meta table (e.g. exposition, class of influence) could help to identify HOBOs with influences?

Michael Stölzle

**Comment by mmaelicke** [comment]
Hi there!
Is there any progress on this issue? If yes, which decissions were made and can the issue be closed?

**Comment by Jeifel** [comment]
> 
> 
> Hi there!
> Is there any progress on this issue? If yes, which decissions were made and can the issue be closed?

Yeah, we will just leave the data in, just like the poll suggests.
