### ISSUE TITLE
task-2, hobo_ids

### ISSUE THREAD

**Issue by manuelhaendel** [data-hydenv/Excercise-06#15]
Task 2 states that 'The view should have one row for each HOBO.' I think that means that we should group by hobo_id (8 digits) and not by id (2-3 digits), what we are currently doing. 
Do you agree?

**Comment by gremax93** [comment]
I'm not sure, it would be kind of confusing for the 2km query, as the result would make no sense because the logger number could be used in 2019 and 2020. However this approach (8 digits )would make it much easyer to impliment the  quality_checked data, as for now there is no commen id to join.

**Comment by manuelhaendel** [comment]
I think that's exactly the intention of this task. To see how much and when the individual loggers were used. Maybe @mmaelicke can clear things up?

**Comment by mmaelicke** [comment]
Ok, this is on me. Not stated very clearly. I intented the 8 digit device hobo id, to obtain per-device statistics. The spatial parts are abit more tricky then (st_union would be a possible way to go)

However, as you already implemented a lot of stuff, choose whichever id fits better for you. **I will accept both versions this year**.

**Comment by mmaelicke** [comment]
I will close this issue, re-open if you need more discussion or clarification.
