### ISSUE TITLE
View function not working correctly when dplyr imported

### ISSUE THREAD

**Issue by mmaelicke** [data-hydenv/Excercise-06#7]
This throws me a _Registered S3 method overwritten by 'dplyr':_ "error" message, but I still get the required table. So I assume it's not a problem; but did anyone else get this?

_Originally posted by @RupDe in https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDY4NzIzOTc1NToyODI2MDM0_

**Comment by zoeschindler** [comment]
I did not get an error o:

**Comment by mmaelicke** [comment]
@data-hydenv/students what about the others? 
[![](https://api.gh-polls.com/poll/01DYSV8ZNQ5BN2GB9ZRWV45HH0/I%20have%20the%20same%20error)](https://api.gh-polls.com/poll/01DYSV8ZNQ5BN2GB9ZRWV45HH0/I%20have%20the%20same%20error/vote)
[![](https://api.gh-polls.com/poll/01DYSV8ZNQ5BN2GB9ZRWV45HH0/I%20don't%20see%20the%20error)](https://api.gh-polls.com/poll/01DYSV8ZNQ5BN2GB9ZRWV45HH0/I%20don't%20see%20the%20error/vote)

**Comment by RupDe** [comment]
Update. Restarted everything and tried to run the code again, I now get this:

Registered S3 method overwritten by 'dplyr':
  method           from
  print.rowwise_df     
Registered S3 methods overwritten by 'dbplyr':
  method         from
  print.tbl_lazy     
  print.tbl_sql      
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.2.1     v purrr   0.3.3
v tibble  2.1.3     v dplyr   0.8.3
v tidyr   1.0.0     v stringr 1.4.0
v readr   1.3.1     v forcats 0.4.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

Attache Paket: �lubridate�

The following object is masked from �package:base�:

    date

**Comment by RupDe** [comment]
Okay, I've done some research and apparently it has something to do with the R version I am running. (_R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"_
_Copyright (C) 2019 The R Foundation for Statistical Computing_
_Platform: x86_64-w64-mingw32/x64 (64-bit)_)

Updating "dplyr" and "dbplyr" got rid of the _Registered S3 methods overwritten by xxx_ part of the error.
(Problem solved, I guess?)

**Comment by mmaelicke** [comment]
Problem solved. I'll close the issue!
